basePath: /
definitions:
  entities.Building:
    properties:
      city:
        type: string
      floors:
        type: integer
      id:
        type: integer
      name:
        type: string
      year:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: evilgooby1@gmail.com
    name: API Support
  description: Add/Get buildings.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /CreateBuilding:
    post:
      consumes:
      - application/json
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: integer
        "418":
          description: I'm a teapot
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      summary: Add in database
      tags:
      - accounts
  /GetBuildings:
    get:
      description: get accounts
      parameters:
      - description: Buildings
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.Building'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: integer
        "418":
          description: I'm a teapot
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      summary: Get from database
      tags:
      - accounts
swagger: "2.0"
